name: {{.Slug}}

services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "{{.HttpPort}}:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: "{{.PgDatabase}}"
      POSTGRES_PASSWORD: "{{.PgPassword}}"
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "{{.AdminerPort}}:8080"

volumes:
  pgdata:
