  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: "{{.PgDatabase}}"
      POSTGRES_PASSWORD: "{{.PgPassword}}"
    volumes:
      - pgdata:/var/lib/postgresql/data
